Feature/add lisk
Adamant-im/adamant-exchangebot pull request #46
Opened 2022-02-11 17:36 UTC by gost3228

Add LISK coin to exchanger

2022-02-27 06:49 UTC, adamant-al commented
Hi,
- base_lsk.js better to name lskBaseCoin.js
- LskBaseCoin should extend baseCoin, not btcBaseCoin
- lisk_utils.js better to name lsk_utils.js
- when user have old account, with previous Lisk core address, the bot say like "Exchange Bot [TEST] thinks transaction of 1 LSK is wrong. Sender expected: 1543470903438799018L, but real sender is lskq524hdpsu4qy5gud74yrtrtvbu8ehkmrja6ptr.". It is because both these addresses saved in ADAMANT's key-value storage, and function getKvsCryptoAddress() took first one. Fix this function with adding "orderBy=timestamp:desc" to a request. See: https://endless.adamant.im/api/states/get?key=lsk:address&senderId=U11452494217613574670&orderBy=timestamp:desc
- Wrong confirmations counting. First time tx seen: "Updated Tx 8bcfc29f2c6ed5… confirmations: -1"
- Fix logging "Successfully built Tx cdb0b9de9… to send 0.66822015 LSK to lskq524… with 0.0016 LSK fee: [object Object]".
- Calculate Lisk tx fee. See src/lib/lisk/lsk-base-api.js in adamant-im.

2022-02-27 07:10 UTC, adamant-al commented on helpers/cryptos/lisk_utils.js
> +   * Not used, additional info: hash (already known), blockId, fee, recipients, senders
Are you sure?

2022-02-27 07:11 UTC, adamant-al commented on package.json
> +    "adamant-api": "github:Adamant-im/adamant-api-jsclient#feature/add-lisk",
Use adamant-api 1.4.0

2022-03-04 13:32 UTC, adamant-al commented on package.json
> +    "adamant-api": "github:Adamant-im/adamant-api-jsclient#feature/add-lisk",
Not yet.

2022-03-24 06:47 UTC, adamant-al commented
@gost3228 Try to change outdated `"lisk-sdk": "^5.2.1"` to newer one. May be even separate modules like `lisk-transactions` and `lisk-cryptography`.

2022-03-24 06:50 UTC, adamant-al commented on package.json
> +    "adamant-api": "github:Adamant-im/adamant-api-jsclient#feature/add-lisk",
To update before merge

2022-03-26 10:38 UTC, MerdyNumber1 commented on .editorconfig
> +tab_width = 2
indent_size is preferable

2022-03-26 10:38 UTC, MerdyNumber1 commented on helpers/cryptos/lskBaseCoin.js
> +    this.account.addressHex = this.account.keys.addressHex;
`this.account = Object.assign(this.account, this.account.keys)`?
Or object `this.account.keys` contains additional keys?

2022-03-26 10:38 UTC, MerdyNumber1 commented on helpers/cryptos/lskBaseCoin.js
> +      if (error.response.data && error.response.data.errors && error.response.data.errors[0] && error.response.data.errors[0].message && error.response.data.errors[0].message.includes('was not found'
You can simplify
`if (error.response?.data?.errors[0]?.message && error.response.data.errors[0].message.includes('was not found'))`

2022-03-26 11:36 UTC, martiliones requested changes

2022-03-26 11:36 UTC, martiliones commented on helpers/cryptos/lskBaseCoin.js
> +    setTimeout(() => this.getLastBlockHeight().then((lastBlockHeight) => log.log(`Last ${this.token} block height: ${utils.isPositiveOrZeroNumber(lastBlockHeight) ? lastBlockHeight : 'unable to recei
Too long line of code. Split into multiple ones

2022-03-26 11:36 UTC, martiliones commented on helpers/cryptos/lsk_utils.js
> +          return Number(data.data.height) || 0;
`(data) => Number(data.data.height) || 0`

2022-03-26 11:36 UTC, martiliones commented on helpers/cryptos/lsk_utils.js
> +    return block ? block : undefined;
`return block || undefined`

2022-03-26 11:36 UTC, martiliones commented on helpers/cryptos/lsk_utils.js
> +        const balance = result.data.token.balance;
`const {balance} = result.data.token`

2022-03-26 11:36 UTC, martiliones commented on helpers/cryptos/lsk_utils.js
> +          try {
what is the 2nd try catch block inside for?

2022-03-26 11:36 UTC, martiliones commented on helpers/cryptos/lsk_utils.js
> +      if (result && result.data[0]) {
remove the `if` statement above and just use `typeof result === 'object'` && result.data[0]`

2022-03-26 11:36 UTC, martiliones commented on helpers/utils.js
> +      hex.push((b & 0xF).toString(16));
can be used one `push` instead. 
```
hex.push(
  (b >>> 4).toString(16),
  (b & 0xF).toString(16)
)
```

2022-03-26 11:36 UTC, martiliones commented on helpers/utils.js
> +      hex.push((b & 0xF).toString(16));
and so the arrow function brackets can be removed

2022-03-28 05:36 UTC, martiliones approved these changes

2022-03-31 08:20 UTC, adamant-al approved these changes

2022-03-31 08:21 UTC, adamant-al commented
@MerdyNumber1 It's your turn.

2022-03-31 16:25 UTC, MerdyNumber1 commented
Excellent

2022-03-31 16:26 UTC, MerdyNumber1 approved these changes

2022-04-01 12:29 UTC, merged